logging:
  level:
    com:
      mcan:
        finartz: TRACE
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
#    url: jdbc:h2:file:C:/Users/Can/workspace/h2
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
